[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "java -Dspring.profiles.active=railway -jar target/multi-level-market-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
startupTimeout = 300

[deploy.envs]
JAVA_OPTS = "-Xmx512m -Xms256m"
SPRING_PROFILES_ACTIVE = "railway"
