name: Deploy to Railway

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      service_id:
        description: "Railway Service ID (overrides repo secret if provided)"
        required: false
        type: string
      environment:
        description: "Deployment environment label (optional)"
        required: false
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Deploy to Railway
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
          RAILWAY_SERVICE_ID: ${{ inputs.service_id != '' && inputs.service_id || secrets.RAILWAY_SERVICE_ID }}
        run: |
          railway login --token "$RAILWAY_TOKEN"
          if [ -n "$RAILWAY_SERVICE_ID" ]; then
            railway up --service "$RAILWAY_SERVICE_ID" --detach
          else
            echo "Railway Service ID not provided via input or secret." >&2
            exit 1
          fi

